[build]
  base = "frontend"
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  PYTHON_VERSION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 